name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      NODE_OPTIONS: --dns-result-order=ipv4first
      NPM_CONFIG_AUDIT: "false"
      NPM_CONFIG_FUND: "false"
      NPM_CONFIG_PROGRESS: "false"
      NPM_CONFIG_STRICT_SSL: "true"
      NPM_CONFIG_FETCH_RETRIES: "5"
      NPM_CONFIG_FETCH_RETRY_MINTIMEOUT: "20000"
      NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT: "120000"
      NPM_CONFIG_NETWORK_TIMEOUT: "300000"
      NPM_CONFIG_NETWORK_CONCURRENCY: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"             # cache em ~/.npm (padrão)

      - name: Pin npm 10.8.2
        run: |
          set -euxo pipefail
          npm --version
          npm i -g npm@10.8.2
          npm --version

      - name: Configurar npm
        run: |
          set -euxo pipefail
          npm config set registry https://registry.npmjs.org/
          npm config set prefer-online true
          npm config get cache    # deve mostrar /home/runner/.npm

      - name: Smoke test NPM CDN (diagnóstico)
        run: |
          set -euxo pipefail
          URL=https://registry.npmjs.org/slash/-/slash-3.0.0.tgz
          curl --ipv4 -I "$URL"
          curl --ipv4 -fsSL --retry 5 --retry-all-errors "$URL" -o /tmp/slash.tgz
          tar -tzf /tmp/slash.tgz >/dev/null

      - name: Instalar dependências (serial e explícito)
        run: |
          set -euxo pipefail
          npm ci --prefer-online --network-concurrency=1 --loglevel=warn

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

      - name: Upload npm logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs
          path: |
            /home/runner/.npm/_logs/*
            npm-debug.log
          if-no-files-found: ignore
